name: ReleaseCI

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        uses: actions/checkout@v2
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: psidex/crowsnest:${{ env.RELEASE_VERSION }}
